### ISSUE TITLE
Nave bar links property.

### ISSUE THREAD

**Issue by shgninc** [savuir/blo#2]
Hi,
In `default.json` file, in section `links`, how can I add some `<a>` tag property?

**Comment by savuir** [comment]
Hi,

Unfortunately it's not available to set `<a>` properties with `default.json` and it's a bit complicated to implement such functionality. The only you can is to fix a base template here: https://github.com/savuir/blo/blob/786d8988ba77652b3260f8bf9ebcb2ae87bdf441/blo/templates/base.html#L39

Glad to see blo looks good in Persian.

**Comment by shgninc** [comment]
Thanks,
So Isn’t any way by jinja or programming in python to solve it?

Your welcome, That's because of the simplicity of blo. 
But I'm new in source codes by python ;-)
